#!/bin/bash 
cd $(cd $(dirname $0); pwd)
RED='\033[0;31m'
SMAY='\033[0;36m' 
GREEN='\033[0;32m'
Yellow='\033[0;33m'
LSAMAY='\033[01;49m'
WHITB='\033[01;90m'
WHITEC='\033[01;91m'
CNIL='\033[0m'


Version=`lsb_release -rs | cut -f1 -d"."`
if [ ! -f "./TG" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Not Dwonload TG .
¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Jesse Source${CNIL} . \n
\n\n"
chmod +x ./ins
./ins
exit;
fi


if [ ! -f "./MaSa/Token.txt" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Token Bot Not Found .
¦ NOW I Run File ${SMAY}./RUN.lua${WHITB} To Enter Data For You Bot${CNIL}. \n
\n\n"
lua ./MaSa/Run.lua
exit;
else
TOKEN=`cat ./MaSa/Token.txt`
BOTID=`echo $TOKEN | cut -f1 -d":"`
Sudo=$(redis-cli get ${BOTID}:SUDO_ID:)
if [[ $Sudo == "" ]]; then
rm -fr ./MaSa/Token.txt
lua ./MaSa/Run.lua
exit;
fi
fi

UserBot=$(redis-cli get ${BOTID}:UserNameBot:)

echo "$Sudo"
echo "$UserBot"

chmod +x ./TG  

python3 -m ./scdlbot/scdlbot

if [ "$1" == "R" ]; then
while true; do
sleep 1s
rm -fr ./AL-MaSa
sudo rm -fr ~/.telegram-cli
./TG -s ./MaSa/Run.lua --bot=$TOKEN
done
else 
if ! screen -list | grep -q "$UserBot"; then
screen -S "$UserBot" ./run R
else
screen -X -S "$UserBot" quit
screen -S "$UserBot" ./run R
fi
fi
